name: Terraform Apply

on:
    push:
        branches:
            - master

jobs:
    terraform:
        runs-on: ubuntu-latest
    
        env:
            ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
            ARM_CLIENT_SECRET: ${{secrets.MYSUPERSECRET}}
            ARM_SUBSCRIPTION_ID: ${{secrets.MYSUBSCRIPTIONID}}
            ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        
        steps:
            - uses: actions/checkout

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1