name: Terraform Plan

on:
    push:
        branches:
            - master

jobs:
    terraform:
        runs-on: ubuntu-latest
    
        steps:
            - uses: owner/repo@ref

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1